baseURL = "https://boldbiosciences.ai/"
languageCode = "en-us"
title = "BOLD Biosciences"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term", "RSS"]

[params]
  description = "BOLD Biosciences — something amazing is brewing."
